# Generated by Django 3.2.8 on 2022-12-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('name', models.CharField(max_length=1024)),
                ('company', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1024)),
                ('message', models.TextField()),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='FeaturedClients',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('name', models.CharField(max_length=512)),
                ('logo', models.FileField(upload_to='featured_clients/')),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('link', models.URLField(max_length=1024)),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('video', models.FileField(upload_to='manifesto/')),
                ('content', models.TextField()),
            ],
            bases=('core.timestamp',),
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('link', models.URLField(max_length=1024)),
                ('image', models.FileField(upload_to='nav_items/')),
            ],
            bases=('core.timestamp',),
        ),
    ]
