# Generated by Django 4.1.4 on 2023-01-05 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestamp')),
                ('link', models.URLField(max_length=1024)),
                ('image', models.FileField(upload_to='pop_up/')),
                ('date', models.DateField(default=datetime.datetime(2023, 1, 5, 19, 38, 44, 410579))),
            ],
            bases=('core.timestamp',),
        ),
        migrations.DeleteModel(
            name='testmodel',
        ),
    ]
