# Generated by Django 4.1.4 on 2023-01-05 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_popup_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 5, 18, 39, 27, 73174, tzinfo=datetime.timezone.utc)),
        ),
    ]
