# Generated by Django 4.1.4 on 2023-01-05 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_popup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
