# Generated by Django 4.1.4 on 2023-01-05 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_popup_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='featuredclients',
            options={'verbose_name': 'Featured Client', 'verbose_name_plural': 'Featured Clients'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Link'},
        ),
        migrations.AlterModelOptions(
            name='manifesto',
            options={'verbose_name': 'Manifesto', 'verbose_name_plural': 'Manifesto'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='popup',
            options={'verbose_name': 'PopUp', 'verbose_name_plural': 'PopUps'},
        ),
        migrations.RenameField(
            model_name='popup',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='links',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popup',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popup',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
